### ISSUE TITLE
"No match for custom ID"

### ISSUE THREAD

**Issue by priyadarshan** [snosov1/toc-org#49] opened 2017-09-20 09:08 UTC
Hi,
I have been using toc-org daily to create TOC for blog posts.

When trying to follow a link in the sample org buffer below I get error:

```
org-link-search: No match for custom ID: h1-header
```

Sample text:

```
* toc :toc:

* h=Heading 1

** h1. Header
Text

** h2. Header
More text

* z=Heading 2

** z1. Header
Other text
```

After calling `toc-org-insert-toc` this is the resulting buffer:

```
* toc :toc:
- [[#hheading-1][h=Heading 1]]
  - [[#h1-header][h1. Header]]
  - [[#h2-header][h2. Header]]
- [[#zheading-2][z=Heading 2]]
  - [[#z1-header][z1. Header]]

* h=Heading 1

** h1. Header

Text

** h2. Header

More text

* z=Heading 2

** z1. Header

Other text
```

Could it be because headers contain `=`? Is there a workaround for this?

Thanks for toc-org.

**Comment by snosov1** [comment] 2017-10-06 07:50
Hey! Sorry for the late response - I was away for some time.

Frankly, I can't reproduce it myself. All the links seem to work fine.  It might be something with org or emacs setup. I've tested on 
```
GNU Emacs 25.1.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.18.9) of 2016-12-08
Org mode version 9.0.1 (9.0.1-elpa @ /home/sergei/.emacs.d/elpa/org-20161118/)
```

 What is yours?

**Comment by priyadarshan** [comment] 2017-10-06 15:05
Hi, I am using this version:

```
GNU Emacs 25.3.1 (amd64-portbld-freebsd11.0, GTK+ Version 3.22.15) of 2017-09-30
```

You are right. I have created a completely blank emacs.d, save MELPA setup and `toc-org`, and the aboce test case is working fine.

It must be something to do with other org settings.

Let me investigate further, I will report back.

**Comment by snosov1** [comment] 2017-10-25 10:50
I'll close this for now. Please, re-open if necessary

**Closed by snosov1** 2017-10-25 10:50 UTC
Labels: can't reproduce

**Comment by priyadarshan** [comment] 2017-10-25 11:15
Thank you for the help.
