### ISSUE TITLE
toc-org makes Gnus prompt to save, for article in org-mode mailing list

### ISSUE THREAD

**Issue by bradyt** [snosov1/toc-org#6] opened 2015-08-07 07:13 UTC
This snippet: 

```
(eval-after-load "org" 
  (lambda () 
    (if (require 'toc-org nil t) 
        (add-hook 'org-mode-hook 'toc-org-enable) 
      (warn "toc-org not found"))))
```

Has the following effect:  

When i access org-mode mailing list with gnus, on certain articles (I guess with org-mode babel blocks) it prompts to save.

**Comment by snosov1** [comment] 2015-08-17 09:43
Hi!

There was a pretty short time period recently, when an org file was saved immediately after opening. This is not the case anymore, so my guess is that something like this shouldn't happen anymore.

Can you, please. double-check this with the most recent version and suggest a way to reproduce this if it still happens?

**Comment by bradyt** [comment] 2015-08-18 07:40
I have toc-org from August 17th. It still occurs. 

My first try at creating a minimal working example didn't work, not sure when I can make a more comprehensive attempt. 

(I was going to say `M-x gnus RET y ^ a nntp RET news.gmane.org`, select orgmode and browse through articles, but this wasn't sufficient in a vm just now, despite enabling toc-org on a hook.)

**Comment by snosov1** [comment] 2015-08-18 08:41
Ok, I'll mark this with `can't reproduce` for now.

Please, update the issue when you have a chance.

**Comment by snosov1** [comment] 2017-03-24 08:29
This issue has rotten a bit. Closing it for now, please, let me know if you still care about it.

**Closed by snosov1** 2017-03-24 08:29 UTC
Labels: can't reproduce
