### ISSUE TITLE
Bug: can't resolve link in TOC when exporting to html

### ISSUE THREAD

**Issue by deb0ch** [snosov1/toc-org#35] opened 2017-01-14 10:36 UTC
I've been experiencing a bug lately when having a table of contents declared as `:TOC:` and then trying to export to html. The error is `Unable to resolve link: <name-of-your-first-heading>`.

Here is a minimal example:

``` org
* toc :TOC:
 - [[#foo][foo]]
 - [[#bar][bar]]
 - [[#baz][baz]]

* foo
Aliquam erat volutpat. Nunc eleifend leo vitae magna. In id erat non orci
commodo lobortis. Proin neque massa, cursus ut, gravida ut, lobortis eget,
lacus. Sed diam. Praesent fermentum tempor tellus.

* bar
Nullam eu ante vel est convallis dignissim. Fusce suscipit, wisi nec facilisis
facilisis, est dui fermentum leo, quis tempor ligula erat quis odio. Nunc porta
vulputate tellus. Nunc rutrum turpis sed pede. Sed bibendum.

* baz
Nullam eu ante vel est convallis dignissim. Fusce suscipit, wisi nec facilisis
facilisis, est dui fermentum leo, quis tempor ligula erat quis odio. Nunc porta
vulputate tellus. Nunc rutrum turpis sed pede. Sed bibendum.
```
then when trying export to html (`M-x org-export-dispatch RET h o` for instance), you get the error `user-error: Unable to resolve link: "foo"` in `*Messages*` and just `Unable to resolve link: "foo"` in the echo area.

A simple workaround is to declare the toc as `:TOC:noexport:`. This way you don't get the error and the toc is still exported, it just doesn't make sense given what `:noexport:` is [supposed to do](http://orgmode.org/manual/Export-settings.html) :confused:

**Comment by snosov1** [comment] 2017-01-25 12:30
Hey, @deb0ch ! 

Thx for the report. 

First, please, let me put your mind into the right place with respect to `:noexport:` tag. Probably, the thing is - after you add `:noexport:` the toc is being generated by the `org-html` export. So, it's not a bug and it's not related to this package =) Simple way to test it is to add `#+OPTIONS: toc:nil` to the top of your file.

Next, to the bug with `Unable to resolve link`. I can also reproduce this, but it doesn't seem like a bug to me. Obviously, you use the "github-style" href format for links but then export to html (that uses a different href format) which causes issues.

There are several options to handle this:
- If you don't want a TOC in exported HTML at all, then use `:noexport:` tag and `#+OPTIONS: toc:nil`
- If you want a TOC in the exported HTML you can utilize the `org` export engine (use `:noexport:` tag, but no `#+OPTIONS: toc:nil`)
-  If you want a TOC in the exported HTML, but want to rely on `toc-org` to generate it, then use `#+OPTIONS: toc:nil` and provide a different "hrefify" function to `toc-org` (instead of github-style one). In the simplest cases, the `org` hrefify function should work. To enable it, simply use `:TOC_2_org:` instead of `:TOC:`

Does it make any sense?

**Comment by snosov1** [comment] 2017-03-24 09:21
Closing as "Not a bug".

**Closed by snosov1** 2017-03-24 09:21 UTC

**Comment by MatthewZMD** [comment] 2019-03-14 01:02
> To enable it, simply use :TOC_2_org:

I tried this, most things worked out nicely. However the generated table of contents has the :TOC_2_org: in it, which doesn't look very good.

**Comment by snosov1** [comment] 2019-03-18 13:27
@MatthewZMD True. Unfortunately, I'm not sure what's the cleanest way to get around it.

You can kinda make it better by adding smth like `#+HTML_HEAD_EXTRA: <style> .TOC_2_org { display: none; } </style>`. Though it still leaves the `tag` span and adds clutter to the source file.
